### PR TITLE
Generate Graphics For survGroup without dependencies

### PR DESCRIPTION
**Pull request by OmarElAshkar**
Hello, 
I inserted a chunk of code into survGroup() to make it generate KM plots of the subsets of geneset combination. This snippet is actually copied from the package and adds no dependencies.

Thank You

### CODE REVIEW

**Review by PoisonAlien — CHANGES_REQUESTED** [review]
Hi,
Thanks for the PR. Would you make the plotting as an optional argument to the function? 

```r
survGroup = function(plot = TRUE, ....)
``` 

Also `coxph()` is duplicated. You might want to remove the unnecessary one and test it for errors.

**Comment by OmarElAshkar** [comment]
@PoisonAlien I think this should do it. I am just wondering if the function run_surv() is used somewhere else. As the plot argument is supposed to be called from exactly the same hierarchy from survGoup(). I passed ellipsis in case the plot argument is added from somewhere else, but would still need a workaround.

**Comment by PoisonAlien** [comment]
You are almost there. I checked it with other TCGA cohorts, and it seems to work - although a couple of fixes are needed. I will merge the PR, and fix them. 
Thank you for your contribution.

**Review by PoisonAlien — COMMENTED** [review]
See the [commen](thttps://github.com/PoisonAlien/maftools/pull/674#issuecomment-790582025) but overall looks okay. I will make some minor changes.

**Pull request merged**
