### PR TITLE
update check action workflow

### PR DESCRIPTION
**Pull request by ShixiangWang**
Dear @PoisonAlien , I am updating the check action workflow based on the latest example of action from https://github.com/r-lib/actions/blob/v2-branch/examples/check-release.yaml

### CODE REVIEW

**Comment by PoisonAlien** [comment]
Thanks a ton @ShixiangWang ! Appreciate your help in maintaining this package :)

**Comment by ShixiangWang** [comment]
You're welcome. Let's see if it works (https://github.com/PoisonAlien/maftools/actions/runs/5541259183/jobs/10114431387?pr=957) before merging.

**Comment by ShixiangWang** [comment]
The action is working. Some warnings about variable names and documentations found @PoisonAlien . You may need to fix them locally.

```
* checking compiled code ... NOTE
File ‘maftools/libs/maftools.so’:
  Found ‘stderr’, possibly from ‘stderr’ (C)
    Object: ‘snpcounts.o’
  Found ‘stdout’, possibly from ‘stdout’ (C)
    Object: ‘snpcounts.o’
File ‘maftools/libs/maftools.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs nor [v]sprintf.
It is good practice to register native routines and to disable symbol
search.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... [86s/87s] OK
Examples with CPU (user + system) or elapsed time > 5s
          user system elapsed
maf2mae 18.386   0.46  18.849
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... [277s/196s] OK
* checking for non-standard things in the check directory ... NOTE
Found the following files/directories:
  ‘laml_clinicalData.txt’ ‘laml_geneSummary.txt’
  ‘laml_gisticCNVSummary.txt’ ‘laml_gisticCytobandSummary.txt’
  ‘laml_gisticData.txt’ ‘laml_gisticGeneSummary.txt’
  ‘laml_maftools.maf’ ‘laml_sampleSummary.txt’ ‘laml_summary.txt’
* checking for detritus in the temp directory ... OK
* DONE

Status: 3 WARNINGs, 8 NOTEs
```

**Comment by PoisonAlien** [comment]
Got it. Thanks, I will clean it up.

**Pull request merged**
