### PR TITLE
Add a co-gisticChromPlot function gisticChromPlot2v and a helper function yload_gistic

### PR DESCRIPTION
**Pull request by biosunsci**
Dear Author @PoisonAlien,

**Issue**

I want to plot a vensus-plot like coOncoplot, to see only Amp or Del G-scores at a time from two GISTIC objects, showing in a gistic Chromesome plot in a vertical layout.  As we often seen in the published papers like Fig.1D in *Hernandez-Verdin, I. et al. Ann Oncol (2023)*.
image

So I wrote a new function named `gisticChromPlot2v` and a helper `yload_gistic`. `2` like `2` in `lollipopPlot2` which means this is a comparison of two GISTIC object and `v` means vertical which is discriminative from the original `gisticChromPlot` which takes a horizonal layout.

**Dependecies**
**Depends**
`magrittr`
**Imports**
`dplyr`

**Command**
After adding these functions we can do coGisticChromPlot using the following codes:

```r
# --- load data ---
all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
scores.gis <- system.file("extdata", "scores.gistic", package = "maftools")

laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis, isTCGA = TRUE)

# or you can use new helper function to quickly read gistic results into new object:
gistic_res_folder = system.file("extdata",package = "maftools")
laml.gistic2 = yload_gistic(gistic_res_folder)
# NOTE:
# to quickly show the plots, I have to use the data inside the maftools, so the left and right part of the plot is mirrored, but
# in practise you will send different GISTIC and MAF objects to `gistic1`,`gistc2`, `maf1`,`maf2`, the function also works well.

laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools') 
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') 
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)
laml2 = laml

# --- plot ---
r = gisticChromPlot2v(gistic1 = laml.gistic, gistic2 = laml.gistic2, type='Del',
                       symmetric = TRUE, g1Name = 'TCGA1',
                       g2Name = 'TCGA2', maf1 = laml, maf2 = laml2, mutGenes = 30)
# will result in
```
image

```r
r = gisticChromPlot2v(gistic1 = laml.gistic, gistic2 = laml.gistic2,  type='Amp',
                       symmetric = FALSE, g1Name = 'TCGA1',
                       g2Name = 'TCGA2', maf1 = laml, maf2 = laml2, mutGenes = NULL)
# will result in
```
image

To clarify the `symmertric` parameter's function, I'll use my own data to show the differences:
If `symmetric` = `FALSE`, `type` = `'Del'` results in:
image
then set `symmetric` = `TRUE` will result to:
image

**This is only the draft, the plot function needs more tests, I'll complete that later**

### CODE REVIEW

**Comment by ShixiangWang** [comment]
Really a good idea. I have some suggestions:

1. Rename it to `coGisticChromPlot` as there is a `coOncoplot` for mutational data.
2. Remove `magrittr` and `dplyr`, instead, use `data.table.

**Comment by PoisonAlien** [comment]
Hi,
Thank you for the PR. Looks very useful. However, as @ShixiangWang suggested, `maftools` doesnt use any tidyverse packages so you will have to change those functions to equivalent `data.table` or base. If you are not comfortable with `data.table` or base syntax, just let me know, I will accept the PR and change the code base accordingly.

**Comment by biosunsci** [comment]
Thx for the suggestions from you and @ShixiangWang.  I'll change the related codes to meet the standard. 
I may need help because I'll not quite familiar with the data.table manipulation.

I have also developed a new helper function currently named `yload_gistic` to auto load gistic object from a GISTIC2.0 output folder. My coding habbit is that all my custom functions start with a 'y' letter.  Is there any suggestions about this function's name to fit maftools' Naming Conventions?
I'am planning to make a vesus plot like this one but exibiting Broad events and Focals events of the same cohort, this function will be useful at that time because it also try to read and store broad data from the result folder.

**Comment by PoisonAlien** [comment]
Hi unfortunately I am not familiar with the dplyr syntax :| 
But its all rite even if you can't change the code base to `data.table`. Just let me know when you think the function is stable and that it works on all your test cases. I will go ahead and accept it, and modify the code accordingly. 

I wouldn't export `yload_gistic`as a separate function, rather keep it internal at the moment.

**Comment by biosunsci** [comment]
> Hi unfortunately I am not familiar with the dplyr syntax :| But its all rite even if you can't change the code base to `data.table`. Just let me know when you think the function is stable and that it works on all your test cases. I will go ahead and accept it, and modify the code accordingly.
> 
> I wouldn't export `yload_gistic`as a separate function, rather keep it internal at the moment.


I've done refine the codes, now there is no need of relying on dplyr. The brach is ready to pull. But the `yload_gistic` still relies on stringr, for usage of two functions from stringr, and I do not know the basic R version of them.

The `yload_gistic` is designed to be exported, it acts as a lazy-man version of `readGistic`, for it only deals with loading data into a GISTIC style like object with nothing others changed. It won't make any difference if we do not use the `yload_gistic`  function at current.

**Comment by ShixiangWang** [comment]
The functions used from `stringr` can be easily replaced by `startsWith()` and `sub()`. 

In the load function, why do you change `18` to `-5`?

**Comment by biosunsci** [comment]
> In the load function, why do you change `18` to `-5`?

I want to get the substrings from the 18th char to the last 5 char. 
After a lot of search, Finally I can get rid of stringr

```R
s = 'abcdefghijklmnopqrstuvwxyz'
stringr::str_sub(s,18,-5) # "rstuv"
sub(s,18,-5) # "-5"
substring(s,18,nchar(s)-4) # "rstuv", but a little bit verbose comparing to `str_sub(s,18,-5)`
```

The basic R's string functions' nomenclature is not consistent, It's hard for a beginner to remember.
That's why I prefer to use tidyverse functions which is more instinctive and concise.

Thanks for providing the `startsWith` solutions.
I've changed the code in the `yload_gistic` which does not depend on `stringr` now.

**Comment by ShixiangWang** [comment]
@biosunsci Thank you for adopting my suggestion. @PoisonAlien Please merge and check :).

**Comment by PoisonAlien** [comment]
Hi @biosunsci ,
Thanks for the PR. Seems to work nicely with my in-house datasets. I will go through the code and do a bit of modifications to `readGistic` as well. 
But quick question, do you really the need data from  `broad_significance_results.txt`?

**Comment by biosunsci** [comment]
Hi @PoisonAlien,

`broad_significance_results.txt` data is Currently not used. But as I want also to make a function to plot Broad vs focal plot like this:
image
At that time the data is needed. I just pre-defined the read function.

I don't think the `readGistic` needs modify for during the usage, there're situations the GISTIC output file names may be changed from the default, so mannually supply the file names is more veratile.
Maybe `yload_gistic` should be a `readGisticFromFolder` rather than an update of `readGistic`.

**Comment by PoisonAlien** [comment]
Fair enough. I have made some changes to your code base. In short,
1. I have removed `yload_gistic` and modified the `readGistic` to import files from gistic directory.
2. `broad_significance_results.txt` is still being read. It is however stored as an [attribute](https://github.com/PoisonAlien/maftools/blob/master/R/readGistic.R#L242) in the `GISTIC` object, that way it is consistent with the package functions. 

Thanks again. Nicely done.

**Comment by ShixiangWang** [comment]
Nice to see these features out! 😃

**Pull request merged**
