### PR TITLE
About oncoplot and oncomatrix

### PR DESCRIPTION
**Pull request by kaigu1990**
Maftools is a perfect tool, I'm used to clinical analysis by maftools
Recently, I find oncoplot don't rely on complexheatmap. There are some discordant layout when I plot oncoplot based on my data. And I also have some personal need, so I update oncoplot and oncomatrix code. Main changes:

* Add anno_height feature to adjust the height of annotation layout
* Adjust the space between each legends because I have ten clinical features to show in graph.
* Add drawBox feature to add a box around main matrix
* Add drawExtraBar feature to replace mutation data in topbar because maybe someone would like show extra numeric cilical data

Visual description is below:
image

### CODE REVIEW

**Comment by PoisonAlien** [comment]
Hi @kaigu1990 ,
Thank you for the modifications, and I am sorry that I couldn;t respond to your earlier issue.
It seems that current PR has some conflicts with master branch. I will go thorough them and merge them accordingly.

**Comment by kaigu1990** [comment]
@PoisonAlien Thank you for your reply. This discordance is result that I added new features not based on least branch. If you think these features are necessary, I can modify these again from least branch.

**Comment by PoisonAlien** [comment]
Can you pull the recent changes from `maftools` master branch and add your changes to it? 
If you think it would be difficult for you then please do let me know. I will take care of it.

**Comment by kaigu1990** [comment]
Ok, I will change and commit it later, maybe 1-3 days.

**Comment by kaigu1990** [comment]
Hi, @PoisonAlien , I have reforked maftoolsclone least version

**Pull request closed without merging**
